# Generated by Django 4.2.4 on 2023-10-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobplatformcred',
            name='id',
            field=models.CharField(auto_created=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
