# Generated by Django 4.2.4 on 2023-10-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0003_alter_jobapplication_id_alter_jobplatformcred_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='platform_cred',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_application.jobplatformcred'),
        ),
    ]
