# Generated by Django 4.2.4 on 2023-10-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0004_jobapplication_platform_cred'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='limit',
            field=models.IntegerField(null=True),
        ),
    ]
