# Generated by Django 4.2.4 on 2023-10-24 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0005_jobapplication_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=255)),
                ('street_number', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('resume', models.URLField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('limit', models.IntegerField()),
                ('visa_required', models.CharField(max_length=10)),
                ('years_experience', models.IntegerField()),
                ('desired_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_application.address')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SearchParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.ManyToManyField(related_name='skills', to='job_application.language')),
                ('softwares', models.ManyToManyField(related_name='skills', to='job_application.software')),
            ],
        ),
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=255)),
                ('search_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_application.searchparams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_application.jobplatformcred')),
            ],
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_application.candidate')),
                ('search_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_application.searchparams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_application.jobplatformcred')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='educations',
            field=models.ManyToManyField(to='job_application.education'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experiences',
            field=models.ManyToManyField(to='job_application.experience'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(related_name='candidates', to='job_application.skill'),
        ),
    ]
