# Generated by Django 4.2.4 on 2023-10-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0006_address_candidate_education_experience_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='start_date',
            field=models.DateField(default='2023-10-17'),
            preserve_default=False,
        ),
    ]
