# Generated by Django 4.2.4 on 2023-10-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0007_candidate_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_application.skill'),
        ),
    ]
